server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\Users\danie\Documents\workspace-sts-3.9.4.RELEASE\Confsvr\src\main\resources\config\geoms


  
#server:
#  port: 8888
#spring:
#  cloud:
#    config:
#      server:
#        encrypt.enabled: false
#        git:
#          uri: https://github.com/dbracamontes/config-repo
#          searchPaths: geoservice,test
#          username: dbracamontes
#          password: daniel51
